import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Achievement definitions
const achievements = [
  // Streak achievements - Short term
  {
    key: 'streak_3',
    name: 'Getting Started',
    description: 'Maintain a 3-day streak',
    icon: 'flame',
    category: 'streak',
    xpReward: 50,
    tier: 'bronze',
    requirement: { type: 'streak', value: 3 },
    isSecret: false,
  },
  {
    key: 'streak_7',
    name: 'Week Warrior',
    description: 'Maintain a 7-day streak',
    icon: 'flame',
    category: 'streak',
    xpReward: 100,
    tier: 'bronze',
    requirement: { type: 'streak', value: 7 },
    isSecret: false,
  },
  {
    key: 'streak_14',
    name: 'Two Week Champion',
    description: 'Maintain a 14-day streak',
    icon: 'flame',
    category: 'streak',
    xpReward: 200,
    tier: 'silver',
    requirement: { type: 'streak', value: 14 },
    isSecret: false,
  },
  {
    key: 'streak_30',
    name: 'Monthly Master',
    description: 'Maintain a 30-day streak',
    icon: 'flame',
    category: 'streak',
    xpReward: 500,
    tier: 'silver',
    requirement: { type: 'streak', value: 30 },
    isSecret: false,
  },
  // Streak achievements - Medium term
  {
    key: 'streak_90',
    name: 'Quarter Champion',
    description: 'Maintain a 3-month streak (90 days)',
    icon: 'flame',
    category: 'streak',
    xpReward: 1000,
    tier: 'gold',
    requirement: { type: 'streak', value: 90 },
    isSecret: false,
  },
  {
    key: 'streak_180',
    name: 'Semester Survivor',
    description: 'Maintain a 6-month streak (180 days)',
    icon: 'flame',
    category: 'streak',
    xpReward: 2000,
    tier: 'gold',
    requirement: { type: 'streak', value: 180 },
    isSecret: false,
  },
  {
    key: 'streak_270',
    name: 'Academic Year Hero',
    description: 'Maintain a 9-month streak (270 days)',
    icon: 'crown',
    category: 'streak',
    xpReward: 3000,
    tier: 'platinum',
    requirement: { type: 'streak', value: 270 },
    isSecret: false,
  },
  // Streak achievements - Long term (yearly)
  {
    key: 'streak_365',
    name: 'Year One',
    description: 'Maintain a 1-year streak (365 days)',
    icon: 'crown',
    category: 'streak',
    xpReward: 5000,
    tier: 'platinum',
    requirement: { type: 'streak', value: 365 },
    isSecret: false,
  },
  {
    key: 'streak_730',
    name: 'Two Year Titan',
    description: 'Maintain a 2-year streak (730 days)',
    icon: 'crown',
    category: 'streak',
    xpReward: 10000,
    tier: 'platinum',
    requirement: { type: 'streak', value: 730 },
    isSecret: false,
  },
  {
    key: 'streak_1095',
    name: 'Three Year Legend',
    description: 'Maintain a 3-year streak (1,095 days)',
    icon: 'crown',
    category: 'streak',
    xpReward: 15000,
    tier: 'platinum',
    requirement: { type: 'streak', value: 1095 },
    isSecret: false,
  },
  {
    key: 'streak_1460',
    name: 'Four Year Graduate',
    description: 'Maintain a 4-year streak (1,460 days)',
    icon: 'graduation-cap',
    category: 'streak',
    xpReward: 20000,
    tier: 'platinum',
    requirement: { type: 'streak', value: 1460 },
    isSecret: false,
  },
  {
    key: 'streak_1825',
    name: 'Half Decade Hero',
    description: 'Maintain a 5-year streak (1,825 days)',
    icon: 'gem',
    category: 'streak',
    xpReward: 25000,
    tier: 'platinum',
    requirement: { type: 'streak', value: 1825 },
    isSecret: false,
  },
  {
    key: 'streak_2190',
    name: 'Six Year Scholar',
    description: 'Maintain a 6-year streak (2,190 days)',
    icon: 'gem',
    category: 'streak',
    xpReward: 30000,
    tier: 'platinum',
    requirement: { type: 'streak', value: 2190 },
    isSecret: false,
  },
  {
    key: 'streak_2555',
    name: 'Seven Year Sage',
    description: 'Maintain a 7-year streak (2,555 days)',
    icon: 'gem',
    category: 'streak',
    xpReward: 35000,
    tier: 'platinum',
    requirement: { type: 'streak', value: 2555 },
    isSecret: false,
  },
  {
    key: 'streak_2920',
    name: 'Eight Year Expert',
    description: 'Maintain a 8-year streak (2,920 days)',
    icon: 'gem',
    category: 'streak',
    xpReward: 40000,
    tier: 'platinum',
    requirement: { type: 'streak', value: 2920 },
    isSecret: false,
  },
  {
    key: 'streak_3285',
    name: 'Nine Year Virtuoso',
    description: 'Maintain a 9-year streak (3,285 days)',
    icon: 'gem',
    category: 'streak',
    xpReward: 45000,
    tier: 'platinum',
    requirement: { type: 'streak', value: 3285 },
    isSecret: false,
  },
  {
    key: 'streak_3650',
    name: 'Decade of Dedication',
    description: 'Maintain a 10-year streak (3,650 days)',
    icon: 'sparkles',
    category: 'streak',
    xpReward: 50000,
    tier: 'platinum',
    requirement: { type: 'streak', value: 3650 },
    isSecret: false,
  },

  // Completion achievements - tracks tasks, assignments, work items, and exams
  {
    key: 'first_task',
    name: 'First Steps',
    description: 'Complete your first item',
    icon: 'star',
    category: 'completion',
    xpReward: 25,
    tier: 'bronze',
    requirement: { type: 'tasks', value: 1 },
    isSecret: false,
  },
  {
    key: 'tasks_10',
    name: 'Getting Things Done',
    description: 'Complete 10 items',
    icon: 'target',
    category: 'completion',
    xpReward: 50,
    tier: 'bronze',
    requirement: { type: 'tasks', value: 10 },
    isSecret: false,
  },
  {
    key: 'tasks_25',
    name: 'Quarter Century',
    description: 'Complete 25 items',
    icon: 'target',
    category: 'completion',
    xpReward: 100,
    tier: 'bronze',
    requirement: { type: 'tasks', value: 25 },
    isSecret: false,
  },
  {
    key: 'tasks_50',
    name: 'Halfway Hero',
    description: 'Complete 50 items',
    icon: 'zap',
    category: 'completion',
    xpReward: 150,
    tier: 'silver',
    requirement: { type: 'tasks', value: 50 },
    isSecret: false,
  },
  {
    key: 'tasks_100',
    name: 'Centurion',
    description: 'Complete 100 items',
    icon: 'trophy',
    category: 'completion',
    xpReward: 300,
    tier: 'silver',
    requirement: { type: 'tasks', value: 100 },
    isSecret: false,
  },
  {
    key: 'tasks_250',
    name: 'Productivity Pro',
    description: 'Complete 250 items',
    icon: 'medal',
    category: 'completion',
    xpReward: 500,
    tier: 'gold',
    requirement: { type: 'tasks', value: 250 },
    isSecret: false,
  },
  {
    key: 'tasks_500',
    name: 'High Achiever',
    description: 'Complete 500 items',
    icon: 'award',
    category: 'completion',
    xpReward: 1000,
    tier: 'gold',
    requirement: { type: 'tasks', value: 500 },
    isSecret: false,
  },
  {
    key: 'tasks_1000',
    name: 'Thousand Club',
    description: 'Complete 1,000 items',
    icon: 'trophy',
    category: 'completion',
    xpReward: 2000,
    tier: 'platinum',
    requirement: { type: 'tasks', value: 1000 },
    isSecret: false,
  },
  {
    key: 'tasks_2500',
    name: 'Overachiever',
    description: 'Complete 2,500 items',
    icon: 'crown',
    category: 'completion',
    xpReward: 5000,
    tier: 'platinum',
    requirement: { type: 'tasks', value: 2500 },
    isSecret: false,
  },
  {
    key: 'tasks_5000',
    name: 'Legendary Scholar',
    description: 'Complete 5,000 items',
    icon: 'gem',
    category: 'completion',
    xpReward: 10000,
    tier: 'platinum',
    requirement: { type: 'tasks', value: 5000 },
    isSecret: false,
  },
  {
    key: 'tasks_10000',
    name: 'Academic Immortal',
    description: 'Complete 10,000 items',
    icon: 'sparkles',
    category: 'completion',
    xpReward: 25000,
    tier: 'platinum',
    requirement: { type: 'tasks', value: 10000 },
    isSecret: false,
  },

  // Consistency achievements - Early Bird (completions before 8 AM)
  {
    key: 'early_bird_5',
    name: 'Early Bird',
    description: 'Complete 5 items before 8 AM',
    icon: 'sun',
    category: 'consistency',
    xpReward: 50,
    tier: 'bronze',
    requirement: { type: 'early_bird', value: 5 },
    isSecret: false,
  },
  {
    key: 'early_bird_25',
    name: 'Early Riser',
    description: 'Complete 25 items before 8 AM',
    icon: 'sun',
    category: 'consistency',
    xpReward: 150,
    tier: 'silver',
    requirement: { type: 'early_bird', value: 25 },
    isSecret: false,
  },
  {
    key: 'early_bird_100',
    name: 'Dawn Champion',
    description: 'Complete 100 items before 8 AM',
    icon: 'sunrise',
    category: 'consistency',
    xpReward: 500,
    tier: 'gold',
    requirement: { type: 'early_bird', value: 100 },
    isSecret: false,
  },
  {
    key: 'early_bird_500',
    name: 'Morning Legend',
    description: 'Complete 500 items before 8 AM',
    icon: 'sunrise',
    category: 'consistency',
    xpReward: 2000,
    tier: 'platinum',
    requirement: { type: 'early_bird', value: 500 },
    isSecret: false,
  },

  // Consistency achievements - Night Owl (completions after 11 PM)
  {
    key: 'night_owl_5',
    name: 'Night Owl',
    description: 'Complete 5 items after 11 PM',
    icon: 'moon',
    category: 'consistency',
    xpReward: 50,
    tier: 'bronze',
    requirement: { type: 'night_owl', value: 5 },
    isSecret: false,
  },
  {
    key: 'night_owl_25',
    name: 'Midnight Scholar',
    description: 'Complete 25 items after 11 PM',
    icon: 'moon',
    category: 'consistency',
    xpReward: 150,
    tier: 'silver',
    requirement: { type: 'night_owl', value: 25 },
    isSecret: false,
  },
  {
    key: 'night_owl_100',
    name: 'Nocturnal Master',
    description: 'Complete 100 items after 11 PM',
    icon: 'moon-star',
    category: 'consistency',
    xpReward: 500,
    tier: 'gold',
    requirement: { type: 'night_owl', value: 100 },
    isSecret: false,
  },
  {
    key: 'night_owl_500',
    name: 'Creature of the Night',
    description: 'Complete 500 items after 11 PM',
    icon: 'moon-star',
    category: 'consistency',
    xpReward: 2000,
    tier: 'platinum',
    requirement: { type: 'night_owl', value: 500 },
    isSecret: false,
  },
];

async function seedAchievements() {
  console.log('Seeding achievements...');

  for (const achievement of achievements) {
    await prisma.achievement.upsert({
      where: { key: achievement.key },
      update: {
        name: achievement.name,
        description: achievement.description,
        icon: achievement.icon,
        category: achievement.category,
        xpReward: achievement.xpReward,
        tier: achievement.tier,
        requirement: achievement.requirement,
        isSecret: achievement.isSecret,
      },
      create: achievement,
    });
    console.log(`  - ${achievement.name}`);
  }

  console.log('Achievements seeded successfully!');
}

seedAchievements()
  .catch((e) => {
    console.error('Error seeding achievements:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
