'use client';

import { useState, useEffect, useRef } from 'react';
import { createPortal } from 'react-dom';
import { Sparkles, X, Loader2, Trash2 } from 'lucide-react';
import Button from '@/components/ui/Button';
import { useAnimatedOpen } from '@/hooks/useModalAnimation';
import previewStyles from '@/components/ItemPreviewModal.module.css';

interface BreakdownStep {
  text: string;
  estimatedMinutes: number;
}

interface AIBreakdownModalProps {
  isOpen: boolean;
  onSave: (checklist: Array<{ id: string; text: string; done: boolean }>) => void;
  onClose: () => void;
  onPremiumRequired: () => void;
  existingTitle?: string;
  existingDescription?: string;
}

export default function AIBreakdownModal({ isOpen, onSave, onClose, onPremiumRequired, existingTitle, existingDescription }: AIBreakdownModalProps) {
  const { visible, closing } = useAnimatedOpen(isOpen);
  const [step, setStep] = useState<'input' | 'review'>(existingDescription ? 'review' : 'input');
  const [inputText, setInputText] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [steps, setSteps] = useState<BreakdownStep[]>([]);
  const autoGeneratedRef = useRef(false);

  // Auto-generate when existingDescription is provided
  useEffect(() => {
    if (existingDescription && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true;
      const text = existingTitle
        ? `${existingTitle}\n\n${existingDescription}`
        : existingDescription;
      runGenerate(text);
    }
  }, [existingDescription]);

  const runGenerate = async (text: string) => {
    if (!text.trim() || isLoading) return;
    setIsLoading(true);
    setError(null);

    try {
      const res = await fetch('/api/work/breakdown', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text }),
      });

      const data = await res.json();

      if (!res.ok) {
        if (data.error === 'premium_required') {
          onClose();
          onPremiumRequired();
          return;
        }
        throw new Error(data.error || 'Failed to generate breakdown');
      }

      setSteps(data.steps || []);
      setStep('review');
    } catch (err: any) {
      setError(err.message || 'Failed to generate breakdown');
    } finally {
      setIsLoading(false);
    }
  };

  const handleGenerate = () => runGenerate(inputText);

  const handleRemoveStep = (index: number) => {
    setSteps(prev => prev.filter((_, i) => i !== index));
  };

  const handleSave = () => {
    const checklist = steps.map((s) => ({
      id: crypto.randomUUID(),
      text: s.estimatedMinutes > 0 ? `${s.text} (~${s.estimatedMinutes}m)` : s.text,
      done: false,
    }));
    onSave(checklist);
    onClose();
  };

  const totalMinutes = steps.reduce((sum, s) => sum + s.estimatedMinutes, 0);
  const hours = Math.floor(totalMinutes / 60);
  const mins = totalMinutes % 60;
  const timeEstimate = hours > 0 ? `${hours}h ${mins}m` : `${mins}m`;

  if (!visible) return null;
  if (typeof document === 'undefined') return null;

  return createPortal(
    <div
      className={closing ? previewStyles.backdropClosing : previewStyles.backdrop}
      style={{ zIndex: 10001 }}
      onClick={() => { if (!isLoading) onClose(); }}
    >
      <div
        className={`${previewStyles.modal} ${closing ? previewStyles.modalClosing : ''}`}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className={previewStyles.header}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Sparkles size={20} style={{ color: 'var(--link)' }} />
            <h2 className={previewStyles.title}>Breakdown</h2>
          </div>
          <button
            onClick={() => { if (!isLoading) onClose(); }}
            className={previewStyles.closeButton}
          >
            <X size={20} />
          </button>
        </div>

        {/* Content */}
        <div className={previewStyles.content} style={{ overscrollBehavior: 'contain' }}>
          {step === 'input' ? (
            <>
              {existingTitle && (
                <p style={{ fontSize: '13px', color: 'var(--text-muted)', margin: 0 }}>
                  Breaking down: <strong style={{ color: 'var(--text)' }}>{existingTitle}</strong>
                </p>
              )}
              <div>
                <label style={{ display: 'block', fontSize: '14px', fontWeight: 500, color: 'var(--text)', marginBottom: '6px' }}>
                  Paste the assignment description
                </label>
                <textarea
                  value={inputText}
                  onChange={(e) => setInputText(e.target.value)}
                  placeholder="Paste the full assignment prompt, project description, or rubric here..."
                  style={{
                    width: '100%',
                    minHeight: '200px',
                    padding: '12px',
                    fontSize: '14px',
                    lineHeight: '1.5',
                    backgroundColor: 'var(--panel-2)',
                    color: 'var(--text)',
                    border: '1px solid var(--border)',
                    borderRadius: '8px',
                    resize: 'vertical',
                    outline: 'none',
                    fontFamily: 'inherit',
                    boxSizing: 'border-box',
                  }}
                />
              </div>
              {error && (
                <p style={{ color: 'var(--danger)', fontSize: '13px', margin: 0 }}>{error}</p>
              )}
            </>
          ) : isLoading ? (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '48px 24px', gap: '16px' }}>
              <Loader2 size={32} className="animate-spin" style={{ color: 'var(--link)' }} />
              <div style={{ fontSize: '14px', color: 'var(--text-muted)' }}>
                Breaking down{existingTitle ? ` "${existingTitle}"` : ''}...
              </div>
            </div>
          ) : error ? (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '48px 24px', gap: '16px' }}>
              <p style={{ color: 'var(--danger)', fontSize: '14px', margin: 0 }}>{error}</p>
            </div>
          ) : (
            <>
              <div style={{ fontSize: '13px', color: 'var(--text-muted)', display: 'flex', justifyContent: 'space-between' }}>
                <span>{steps.length} subtask{steps.length !== 1 ? 's' : ''}</span>
                <span>Est. total: {timeEstimate}</span>
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                {steps.map((s, i) => (
                  <div
                    key={i}
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: '10px',
                      padding: '10px 12px',
                      backgroundColor: 'var(--panel-2)',
                      borderRadius: '8px',
                    }}
                  >
                    <div style={{ flex: 1, minWidth: 0 }}>
                      <div style={{ fontSize: '14px', color: 'var(--text)', wordBreak: 'break-word' }}>{s.text}</div>
                      {s.estimatedMinutes > 0 && (
                        <div style={{ fontSize: '12px', color: 'var(--text-muted)', marginTop: '2px' }}>~{s.estimatedMinutes}m</div>
                      )}
                    </div>
                    <button
                      onClick={() => handleRemoveStep(i)}
                      className={previewStyles.closeButton}
                      style={{ flexShrink: 0 }}
                    >
                      <Trash2 size={14} />
                    </button>
                  </div>
                ))}
              </div>
            </>
          )}
        </div>

        {/* Footer */}
        <div className={previewStyles.footer}>
          {step === 'input' ? (
            <>
              <Button variant="secondary" style={{ flex: 1 }} onClick={onClose} disabled={isLoading}>
                Cancel
              </Button>
              <Button variant="primary" style={{ flex: 1 }} onClick={handleGenerate} disabled={isLoading || !inputText.trim()}>
                {isLoading ? (
                  <><Loader2 size={16} className="animate-spin" /> Generating...</>
                ) : (
                  <><Sparkles size={16} /> Generate Subtasks</>
                )}
              </Button>
            </>
          ) : error ? (
            <>
              <Button variant="secondary" style={{ flex: 1 }} onClick={onClose}>
                Cancel
              </Button>
              <Button variant="primary" style={{ flex: 1 }} onClick={() => {
                if (existingDescription) {
                  const text = existingTitle ? `${existingTitle}\n\n${existingDescription}` : existingDescription;
                  runGenerate(text);
                } else {
                  setStep('input');
                  setError(null);
                }
              }}>
                Retry
              </Button>
            </>
          ) : !isLoading ? (
            <>
              <Button variant="secondary" style={{ flex: 1 }} onClick={onClose}>
                Cancel
              </Button>
              <Button variant="primary" style={{ flex: 1 }} onClick={handleSave} disabled={steps.length === 0}>
                Save to Checklist
              </Button>
            </>
          ) : null}
        </div>
      </div>
    </div>,
    document.body
  );
}
