export interface SearchableItem {
  id: string;
  title: string;
  description?: string;
  keywords: string[];
  category: 'page' | 'tool' | 'setting' | 'dashboard' | 'item';
  categoryLabel: string;
  href: string;
  tab?: string;
  elementId?: string;
  isPremium?: boolean;
  // For dynamic items that open modals
  action?: 'navigate' | 'openModal';
  itemType?: 'work' | 'exam' | 'event' | 'course' | 'note' | 'deck' | 'shopping' | 'folder';
  itemId?: string;
  itemData?: any; // The full item data for modal display
}

export const SEARCH_INDEX: SearchableItem[] = [
  // ==================== PAGES ====================
  {
    id: 'page-dashboard',
    title: 'Dashboard',
    description: 'Your home page with timeline, progress, and quick links',
    keywords: ['home', 'main', 'overview', 'timeline', 'progress'],
    category: 'page',
    categoryLabel: 'Pages',
    href: '/',
  },
  {
    id: 'page-calendar',
    title: 'Calendar',
    description: 'View and manage your schedule',
    keywords: ['schedule', 'events', 'dates', 'month', 'week', 'day'],
    category: 'page',
    categoryLabel: 'Pages',
    href: '/calendar',
  },
  {
    id: 'page-work',
    title: 'Work',
    description: 'Manage tasks, assignments, readings, and projects',
    keywords: ['tasks', 'assignments', 'homework', 'readings', 'projects', 'todo', 'to-do', 'deadlines'],
    category: 'page',
    categoryLabel: 'Pages',
    href: '/work',
  },
  {
    id: 'page-exams',
    title: 'Exams',
    description: 'Track your upcoming exams and tests',
    keywords: ['tests', 'quizzes', 'midterm', 'final', 'exam schedule'],
    category: 'page',
    categoryLabel: 'Pages',
    href: '/exams',
  },
  {
    id: 'page-notes',
    title: 'Notes',
    description: 'Create and organize your notes',
    keywords: ['note taking', 'documents', 'markdown', 'folders'],
    category: 'page',
    categoryLabel: 'Pages',
    href: '/notes',
  },
  {
    id: 'page-courses',
    title: 'Courses',
    description: 'Manage your enrolled courses',
    keywords: ['classes', 'subjects', 'schedule', 'professors', 'instructors'],
    category: 'page',
    categoryLabel: 'Pages',
    href: '/courses',
  },
  {
    id: 'page-shopping',
    title: 'Shopping',
    description: 'Grocery lists, wishlists, and pantry tracking',
    keywords: ['grocery', 'wishlist', 'pantry', 'shopping list', 'buy'],
    category: 'page',
    categoryLabel: 'Pages',
    href: '/shopping',
  },
  {
    id: 'page-tools',
    title: 'Tools',
    description: 'Productivity and grade calculation tools',
    keywords: ['utilities', 'calculator', 'timer', 'pomodoro'],
    category: 'page',
    categoryLabel: 'Pages',
    href: '/tools',
  },
  {
    id: 'page-progress',
    title: 'Progress',
    description: 'Track your achievements and statistics',
    keywords: ['stats', 'statistics', 'achievements', 'badges', 'gamification', 'level', 'xp'],
    category: 'page',
    categoryLabel: 'Pages',
    href: '/progress',
  },
  {
    id: 'progress-daily-challenges',
    title: 'Daily Challenges',
    description: 'Complete 3 daily challenges for XP rewards',
    keywords: ['daily', 'challenges', 'daily challenges', 'sweep', 'bonus', 'xp reward'],
    category: 'page',
    categoryLabel: 'Progress',
    href: '/progress',
    elementId: 'daily-challenges',
  },
  {
    id: 'page-account',
    title: 'Account',
    description: 'Manage your account settings and subscription',
    keywords: ['profile', 'subscription', 'billing', 'premium', 'password', 'email'],
    category: 'page',
    categoryLabel: 'Pages',
    href: '/account',
  },
  {
    id: 'page-flashcards',
    title: 'Flashcards',
    description: 'Create and study flashcards with spaced repetition',
    keywords: ['flashcards', 'study', 'memorize', 'review', 'spaced repetition', 'sm2', 'decks', 'cards', 'match', 'type answer', 'study modes', 'quiz'],
    category: 'page',
    categoryLabel: 'Pages',
    href: '/flashcards',
  },

  // ==================== TOOLS ====================
  {
    id: 'tool-pomodoro',
    title: 'Pomodoro Timer',
    description: 'Focus timer with work and break intervals',
    keywords: ['focus', 'timer', 'productivity', 'concentration', 'study timer', '25 minutes'],
    category: 'tool',
    categoryLabel: 'Tools > Productivity',
    href: '/tools',
    tab: 'productivity',
    elementId: 'pomodoro-timer',
  },
  {
    id: 'tool-file-converter',
    title: 'File Converter',
    description: 'Convert files between different formats',
    keywords: ['convert', 'pdf', 'image', 'document', 'format'],
    category: 'tool',
    categoryLabel: 'Tools > Productivity',
    href: '/tools',
    tab: 'productivity',
    elementId: 'file-converter',
  },
  {
    id: 'tool-quick-links',
    title: 'Quick Links',
    description: 'Access your university links and custom shortcuts',
    keywords: ['links', 'shortcuts', 'university', 'portal', 'bookmarks'],
    category: 'tool',
    categoryLabel: 'Tools > Productivity',
    href: '/tools',
    tab: 'productivity',
    elementId: 'quick-links',
  },
  {
    id: 'tool-word-counter',
    title: 'Word Counter',
    description: 'Count words, characters, sentences, and paragraphs',
    keywords: ['word count', 'character count', 'essay', 'writing', 'text analysis', 'reading time'],
    category: 'tool',
    categoryLabel: 'Tools > Productivity',
    href: '/tools',
    tab: 'productivity',
    elementId: 'word-counter',
  },
  {
    id: 'tool-unit-converter',
    title: 'Unit Converter',
    description: 'Convert between length, weight, temperature, and more',
    keywords: ['unit', 'convert', 'measurement', 'metric', 'imperial', 'length', 'weight', 'temperature', 'volume'],
    category: 'tool',
    categoryLabel: 'Tools > Productivity',
    href: '/tools',
    tab: 'productivity',
    elementId: 'unit-converter',
  },
  {
    id: 'tool-citation-generator',
    title: 'Citation Generator',
    description: 'Generate citations in APA, MLA, Chicago, and more formats',
    keywords: ['citation', 'reference', 'bibliography', 'apa', 'mla', 'chicago', 'harvard', 'works cited'],
    category: 'tool',
    categoryLabel: 'Tools > Productivity',
    href: '/tools',
    tab: 'productivity',
    elementId: 'citation-generator',
  },
  {
    id: 'tool-grade-tracker',
    title: 'Grade Tracker',
    description: 'Track grades for each course',
    keywords: ['grades', 'scores', 'marks', 'assignments', 'course grades'],
    category: 'tool',
    categoryLabel: 'Tools > Grades & GPA',
    href: '/tools',
    tab: 'grades',
    elementId: 'grade-tracker',
  },
  {
    id: 'tool-gpa-calculator',
    title: 'GPA Calculator',
    description: 'Calculate your GPA from course grades',
    keywords: ['gpa', 'grade point average', 'calculate', 'cumulative'],
    category: 'tool',
    categoryLabel: 'Tools > Grades & GPA',
    href: '/tools',
    tab: 'grades',
    elementId: 'gpa-calculator',
  },
  {
    id: 'tool-gpa-trend',
    title: 'GPA Trend Chart',
    description: 'Visualize your GPA over time',
    keywords: ['gpa', 'chart', 'graph', 'trend', 'history', 'visualization'],
    category: 'tool',
    categoryLabel: 'Tools > Grades & GPA',
    href: '/tools',
    tab: 'grades',
    elementId: 'gpa-trend',
  },
  {
    id: 'tool-what-if',
    title: 'What-If GPA Projector',
    description: 'Project your GPA with hypothetical grades',
    keywords: ['what if', 'project', 'gpa', 'predict', 'hypothetical', 'simulate'],
    category: 'tool',
    categoryLabel: 'Tools > Grades & GPA',
    href: '/tools',
    tab: 'grades',
    elementId: 'whatif-projector',
  },
  {
    id: 'tool-final-grade',
    title: 'Final Grade Calculator',
    description: 'Calculate what grade you need on your final',
    keywords: ['final', 'exam', 'grade needed', 'calculate', 'target'],
    category: 'tool',
    categoryLabel: 'Tools > Grades & GPA',
    href: '/tools',
    tab: 'grades',
    elementId: 'final-grade-calculator',
  },

  // ==================== CALENDAR ====================
  {
    id: 'calendar-excluded-dates',
    title: 'Excluded Dates & Holidays',
    description: 'Manage school holidays and cancelled classes',
    keywords: ['excluded', 'dates', 'holidays', 'no school', 'cancelled', 'break', 'vacation', 'off'],
    category: 'tool',
    categoryLabel: 'Calendar',
    href: '/calendar',
    elementId: 'excluded-dates',
  },

  // ==================== SETTINGS - APPEARANCE ====================
  {
    id: 'setting-theme',
    title: 'Theme',
    description: 'Switch between light and dark mode',
    keywords: ['dark mode', 'light mode', 'appearance', 'color scheme', 'night mode'],
    category: 'setting',
    categoryLabel: 'Settings > Appearance',
    href: '/settings',
    tab: 'appearance',
    elementId: 'setting-theme',
  },
  {
    id: 'setting-university',
    title: 'University Colors',
    description: 'Choose your university for themed colors',
    keywords: ['college', 'school', 'colors', 'theme', 'university'],
    category: 'setting',
    categoryLabel: 'Settings > Appearance',
    href: '/settings',
    tab: 'appearance',
    elementId: 'setting-university',
  },
  {
    id: 'setting-custom-theme',
    title: 'Custom Theme',
    description: 'Create your own custom color theme',
    keywords: ['custom colors', 'personalize', 'accent', 'theme editor'],
    category: 'setting',
    categoryLabel: 'Settings > Appearance',
    href: '/settings',
    tab: 'appearance',
    elementId: 'setting-custom-theme',
    isPremium: true,
  },
  {
    id: 'setting-glow-intensity',
    title: 'Glow Intensity',
    description: 'Adjust the glow effect intensity',
    keywords: ['glow', 'effects', 'visual', 'intensity'],
    category: 'setting',
    categoryLabel: 'Settings > Appearance',
    href: '/settings',
    tab: 'appearance',
    elementId: 'setting-glow-intensity',
    isPremium: true,
  },
  {
    id: 'setting-gradient-intensity',
    title: 'Gradient Intensity',
    description: 'Adjust the gradient effect intensity',
    keywords: ['gradient', 'effects', 'visual', 'intensity'],
    category: 'setting',
    categoryLabel: 'Settings > Appearance',
    href: '/settings',
    tab: 'appearance',
    elementId: 'setting-gradient-intensity',
    isPremium: true,
  },
  {
    id: 'setting-visual-theme',
    title: 'Visual Themes',
    description: 'Choose from 20+ visual themes with unique backgrounds and animations',
    keywords: ['visual theme', 'themes', 'background', 'animation', 'aquarium', 'ocean', 'space', 'sakura', 'pixel', 'lofi', 'cozy', 'random theme'],
    category: 'setting',
    categoryLabel: 'Settings > Appearance',
    href: '/settings',
    tab: 'appearance',
    elementId: 'setting-visual-theme',
    isPremium: true,
  },
  {
    id: 'setting-pet-companion',
    title: 'Pet Companion',
    description: 'Choose an animated pixel art pet that walks along the bottom of your screen',
    keywords: ['pet', 'companion', 'animal', 'dog', 'fox', 'turtle', 'parrot', 'pixel art', 'animated'],
    category: 'setting',
    categoryLabel: 'Settings > Appearance',
    href: '/settings',
    tab: 'appearance',
    elementId: 'setting-pet-companion',
    isPremium: true,
  },
  {
    id: 'setting-colorblind-mode',
    title: 'Colorblind Mode',
    description: 'Enable colorblind-friendly colors',
    keywords: ['accessibility', 'colorblind', 'a11y', 'deuteranopia', 'protanopia', 'tritanopia'],
    category: 'setting',
    categoryLabel: 'Settings > Appearance',
    href: '/settings',
    tab: 'appearance',
    elementId: 'setting-colorblind-mode',
  },
  {
    id: 'setting-visible-pages',
    title: 'Visible Pages',
    description: 'Customize which pages appear in the navigation',
    keywords: ['navigation', 'sidebar', 'hide pages', 'show pages', 'customize'],
    category: 'setting',
    categoryLabel: 'Settings > Appearance',
    href: '/settings',
    tab: 'appearance',
    elementId: 'setting-visible-pages',
    isPremium: true,
  },
  {
    id: 'setting-visible-tools',
    title: 'Visible Tools',
    description: 'Customize which tools are visible',
    keywords: ['tools', 'hide', 'show', 'customize'],
    category: 'setting',
    categoryLabel: 'Settings > Appearance',
    href: '/settings',
    tab: 'appearance',
    elementId: 'setting-visible-tools',
    isPremium: true,
  },

  // ==================== SETTINGS - PREFERENCES ====================
  {
    id: 'setting-due-soon-days',
    title: 'Due Soon Days',
    description: 'Set how many days ahead to show "due soon" items',
    keywords: ['due soon', 'days', 'deadline', 'upcoming'],
    category: 'setting',
    categoryLabel: 'Settings > Preferences',
    href: '/settings',
    tab: 'preferences',
    elementId: 'setting-due-soon-days',
  },
  {
    id: 'setting-keyboard-shortcuts',
    title: 'Keyboard Shortcuts',
    description: 'Enable or disable keyboard shortcuts',
    keywords: ['keyboard', 'shortcuts', 'hotkeys', 'keybindings'],
    category: 'setting',
    categoryLabel: 'Settings > Preferences',
    href: '/settings',
    tab: 'preferences',
    elementId: 'setting-keyboard-shortcuts',
  },
  {
    id: 'setting-confirm-delete',
    title: 'Confirm Before Delete',
    description: 'Show confirmation when deleting items',
    keywords: ['delete', 'confirm', 'safety', 'undo'],
    category: 'setting',
    categoryLabel: 'Settings > Preferences',
    href: '/settings',
    tab: 'preferences',
    elementId: 'setting-confirm-delete',
  },
  {
    id: 'setting-nav-counts',
    title: 'Navigation Counts',
    description: 'Show item counts in the navigation sidebar',
    keywords: ['counts', 'badges', 'navigation', 'sidebar'],
    category: 'setting',
    categoryLabel: 'Settings > Preferences',
    href: '/settings',
    tab: 'preferences',
    elementId: 'setting-nav-counts',
  },
  {
    id: 'setting-vacation-mode',
    title: 'Vacation Mode',
    description: 'Pause notifications and reminders while on vacation',
    keywords: ['vacation', 'holiday', 'break', 'pause notifications'],
    category: 'setting',
    categoryLabel: 'Settings > Preferences',
    href: '/settings',
    tab: 'preferences',
    elementId: 'setting-vacation-mode',
  },
  {
    id: 'setting-notifications',
    title: 'Notification Preferences',
    description: 'Configure email and push notifications',
    keywords: ['notifications', 'email', 'push', 'reminders', 'alerts'],
    category: 'setting',
    categoryLabel: 'Settings > Preferences',
    href: '/settings',
    tab: 'preferences',
    elementId: 'setting-notifications',
  },
  {
    id: 'setting-reminder-timing',
    title: 'Reminder Timing',
    description: 'Set when to receive reminders for exams, deadlines, and tasks',
    keywords: ['reminders', 'timing', 'schedule', 'advance notice'],
    category: 'setting',
    categoryLabel: 'Settings > Preferences',
    href: '/settings',
    tab: 'preferences',
    elementId: 'setting-reminder-timing',
  },

  // ==================== SETTINGS - INTEGRATIONS ====================
  {
    id: 'setting-canvas',
    title: 'Canvas LMS',
    description: 'Connect to Canvas to sync courses and assignments',
    keywords: ['canvas', 'lms', 'sync', 'integration', 'learning management'],
    category: 'setting',
    categoryLabel: 'Settings > Integrations',
    href: '/settings',
    tab: 'integrations',
    elementId: 'setting-canvas',
  },
  {
    id: 'setting-blackboard',
    title: 'Blackboard',
    description: 'Connect to Blackboard to sync courses and assignments',
    keywords: ['blackboard', 'lms', 'sync', 'integration', 'learning management'],
    category: 'setting',
    categoryLabel: 'Settings > Integrations',
    href: '/settings',
    tab: 'integrations',
    elementId: 'setting-blackboard',
  },
  {
    id: 'setting-moodle',
    title: 'Moodle',
    description: 'Connect to Moodle to sync courses and assignments',
    keywords: ['moodle', 'lms', 'sync', 'integration', 'learning management'],
    category: 'setting',
    categoryLabel: 'Settings > Integrations',
    href: '/settings',
    tab: 'integrations',
    elementId: 'setting-moodle',
  },
  {
    id: 'setting-brightspace',
    title: 'Brightspace (D2L)',
    description: 'Connect to Brightspace to sync courses and assignments',
    keywords: ['brightspace', 'd2l', 'lms', 'sync', 'integration', 'learning management'],
    category: 'setting',
    categoryLabel: 'Settings > Integrations',
    href: '/settings',
    tab: 'integrations',
    elementId: 'setting-brightspace',
  },
  {
    id: 'setting-google-calendar',
    title: 'Google Calendar',
    description: 'Sync your schedule with Google Calendar',
    keywords: ['google', 'calendar', 'sync', 'gcal', 'export'],
    category: 'setting',
    categoryLabel: 'Settings > Integrations',
    href: '/settings',
    tab: 'integrations',
    elementId: 'setting-google-calendar',
  },

  // ==================== ACCOUNT DATA MANAGEMENT ====================
  {
    id: 'account-export-data',
    title: 'Export Data',
    description: 'Download all your data as JSON',
    keywords: ['export', 'download', 'backup', 'data'],
    category: 'page',
    categoryLabel: 'Account',
    href: '/account',
    elementId: 'account-export-data',
  },
  {
    id: 'account-import-data',
    title: 'Import Data',
    description: 'Import data from a backup file',
    keywords: ['import', 'upload', 'restore', 'backup'],
    category: 'page',
    categoryLabel: 'Account',
    href: '/account',
    elementId: 'account-import-data',
  },
  {
    id: 'account-delete-data',
    title: 'Delete All Data',
    description: 'Permanently delete all your data',
    keywords: ['delete', 'clear', 'reset', 'remove data'],
    category: 'page',
    categoryLabel: 'Account',
    href: '/account',
    elementId: 'account-delete-data',
  },

  // ==================== SETTINGS - ABOUT ====================
  {
    id: 'setting-request-college',
    title: 'Request a College',
    description: 'Request your college to be added to the color themes',
    keywords: ['request', 'college', 'university', 'add school'],
    category: 'setting',
    categoryLabel: 'Settings > About',
    href: '/settings',
    tab: 'about',
    elementId: 'setting-request-college',
  },
  {
    id: 'setting-report-issue',
    title: 'Report an Issue',
    description: 'Report a bug or problem',
    keywords: ['bug', 'issue', 'problem', 'report', 'feedback'],
    category: 'setting',
    categoryLabel: 'Settings > About',
    href: '/settings',
    tab: 'about',
    elementId: 'setting-report-issue',
  },
  {
    id: 'setting-feature-request',
    title: 'Feature Request',
    description: 'Suggest a new feature',
    keywords: ['feature', 'request', 'suggestion', 'idea', 'feedback'],
    category: 'setting',
    categoryLabel: 'Settings > About',
    href: '/settings',
    tab: 'about',
    elementId: 'setting-feature-request',
  },

  // ==================== DASHBOARD CARDS ====================
  {
    id: 'dashboard-timeline',
    title: 'Timeline',
    description: 'Your upcoming events and deadlines',
    keywords: ['timeline', 'upcoming', 'schedule', 'events'],
    category: 'dashboard',
    categoryLabel: 'Dashboard',
    href: '/',
    elementId: 'timeline',
  },
  {
    id: 'dashboard-progress',
    title: 'Your Progress',
    description: 'Track your achievements and level',
    keywords: ['progress', 'achievements', 'level', 'xp', 'stats'],
    category: 'dashboard',
    categoryLabel: 'Dashboard',
    href: '/',
    elementId: 'progress',
  },
  {
    id: 'dashboard-quick-links',
    title: 'Quick Links',
    description: 'Access frequently used links',
    keywords: ['links', 'shortcuts', 'quick access'],
    category: 'dashboard',
    categoryLabel: 'Dashboard',
    href: '/',
    elementId: 'dashboard_quickLinks',
  },
];
